version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  flower:
    image: mher/flower:latest
    environment:
      FLOWER_PORT : 5555
      CELERY_BROKER_URL: "redis://redis:6379/0"
      FLOWER_BROKER_API: "redis://redis:6379/0"
    expose:
      - 5555
    ports:
      - '5555:5555'
    depends_on:
      - redis
  fastapi_app:
    build:
        context: .
        dockerfile: Dockerfile.fastapi
    image: fastapi-app:latest
    expose:
      - 8080
    ports:
      - '8080:8080'
    depends_on:
      - redis
  celery_app:
    build:
        context: .
        dockerfile: Dockerfile.celery_app
    image: celery-app:latest
    depends_on:
      - redis

volumes:
  cache:
    driver: local
